### ISSUE TITLE
Home - June Version

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-website-2019#1]
### Home page
Ideas that needs discussion to clarify what we want and can achieve for June version.

## P1
- [x] **Nav**
- Will it be mozilla festival content only? **Yes**

- [x] **Hero Area**  
- Full-width banner with cta? _probably_

- [x]  **Blog/News** 
- Perhaps can be automated via tags if engineering team can build in time
- Back Up: To pull from medium via pulse

- [x] **Footer**
- Which footer to use? Mozilla festival email component? Foundation site footer?
- Should the social links to be specific to mozilla festival? (youtube, medium, twitter, etc.)

## P2

- [ ] **Social Feed Embed**
- To pull from #mozfest or mozillafestival twitter?

________________________________
### Draft Wireframe
Content for placement only.
<img width="300" src=https://user-images.githubusercontent.com/2492510/55358525-782ad500-5484-11e9-9778-62d4447e7b04.png>

**Comment by beccaklam** [comment]
@sabrinang do we need blog/news and social feeds? The 2018 MozFest homepage doesn't seem to have either?

**Comment by sabrinang** [comment]
@beccaklam 

Yeah I think these items are up for discussion so good to point out we should scope out if feeds are needs or a nice-to-haves on a technical and programing level for June. 

Zannah expressed the intent to surface more storytelling this year and I believe publishing stories is one of their KRs so I'd prioritize surfacing latest news/blogs (as medium is the platform she'll be using) over social as it seems like a nice-to have.

**Comment by beccaklam** [comment]
@sabrinang thanks! I updated the ticket with P1s and P2s and a checklist for us to work with as we get things done.

**Comment by beccaklam** [comment]
@sabrinang who can answer all of our questions? re: footer, links, nav? or is this for us to decide?

**Comment by gideonthomas** [comment]
@beccaklam sorry it's so complicated but it's from a few sources - @alanmoo can offer input about what's feasible engineering-wise by June. @sabrinang and team make decisions about everything else with input and feedback from Zannah.

To make this easier, I'll try my best to collect as much information as possible from the different stakeholders and add the info to tickets, so feel free to ask these questions in the tickets.

**Comment by gideonthomas** [comment]
- **Nav**: MozFest team has indicated their strong preference for MozFest-only nav. So if feasible, let's try to do this if possible engineering-wise and makes sense UX-wise.

- **Blog/News**: @zee-moz would like to use something like the "Latest News" section on the foundation site homepage. Check with @alanmoo if that is technically possible and see if it makes sense UI-wise. If not, we would use the Pulse gallery component and use the checkbox to skip Pulse and go directly to the medium post.

- **Newsletter signup**: @zee-moz has concerns about the newsletter sign up being so low on the page when it's still a high CTA at that point of time. Is there a better way to feature it on the page (chat with @zee-moz to identify the use case)? If not, design team can make the decision about whatever is the best UX after conferring with @alanmoo about any engineering work that would be needed for this being ready for June.

- **Hero Area**: @zee-moz - what would you prefer there, then the design team can decide. @sabrinang suggestion: maybe that is a good area to showcase the main CTA for that period and have the top-right button be the newsletter subscription somehow?

- **Footer and Social links**: Really good question and I'm not sure who owns that piece at the moment. I can find this out and update here.

**Comment by alanmoo** [comment]
>Nav: MozFest team has indicated their strong preference for MozFest-only nav. So if feasible, let's try to do this if possible engineering-wise and makes sense UX-wise.

This makes sense, but it would be best to keep this in line with the current site nav styling so we just switch text/links out. Using a new base does give us the opportunity to switch out a few other things related to the separate domain anyway, like analytics.

>Blog/News: @zee-moz would like to use something like the "Latest News" section on the foundation site homepage. Check with @alanmoo if that is technically possible and see if it makes sense UI-wise. If not, we would use the Pulse gallery component and use the checkbox to skip Pulse and go directly to the medium post.

I'd like to see this automatically pull from a feed instead of having to manually declare each item to be shown on the page as we currently do. Either way requires some amount of engineering work, and the former is more reusable across the site. I see this happening when we get to "related articles" on blog posts which necessitate tagging. That being said, it's a fair amount of work to make that all happen and I think keeping our eye on Pulse gallery as a backup is wise, because that's mostly as simple as "enable streamfield" from an engineering standpoint.

>Newsletter signup: @zee-moz has concerns about the newsletter sign up being so low on the page when it's still a high CTA at that point of time. Is there a better way to feature it on the page (chat with @zee-moz to identify the use case)? If not, design team can make the decision about whatever is the best UX after conferring with @alanmoo about any engineering work that would be needed for this being ready for June.

We should be able to leverage the same page header newsletter signup that we're going to be building for the main foundation site, if that's a reasonable option (sitting next to the "submit a proposal" button).

**Comment by zee-moz** [comment]
hi @alanmoo @beccaklam @sabrinang 
Just following up on the blog/news convo. I'm putting a bit of time into profiles of MozFest people to really give potential attendees a sense of the the range of amazing stuff that happens at the Festival-- by June I aim to have 4 to 8 stories, so I really would love to highlight these. 
[Here's an example of one I've already published.](https://medium.com/mozilla-festival/catching-up-with-gretchen-andrew-search-engine-artist-e6315255ab72) Without a dedicated social media person on staff, we have fewer resources  to share/promote these, so highlighting them on the site is super super important. With Pulse, is there an extra clickthru from MozFest home to Pulse to Medium?  That would be unacceptable IMHO. cc @gideonthomas

**Comment by alanmoo** [comment]
No extra click through- we recently made it possible to avoid that. The cards on [this page](https://foundation.mozilla.org/en/advocacy/) are from pulse, but you’ll see the links are direct.

**Comment by beccaklam** [comment]
Hey @alanmoo just picking this work back up after our content discovery meeting. Some questions:
- Are we able to do a MozFest specific footer? See redpen [here](https://redpen.io/smaff9809d00feddb3)
- And would we be able to do social embeds? Like a twitter feed? Also see the previous redpen

**Comment by alanmoo** [comment]
Footer: Yup, that was expected.
Social feed: Yes, but not with much (if any) custom styling beyond whatever Twitter gives us automatically.

**Comment by sabrinang** [comment]
Zannah's June Content gdoc: https://docs.google.com/document/d/12u63_FzPOEWvR1l_PLmT84Wj0nKpm3VgVuYofVo6m3E/edit#

Updated redpen with copy: https://redpen.io/vuefbd37973f0c2a38/2

![image](https://user-images.githubusercontent.com/2492510/57734379-9a546d00-7656-11e9-8991-b6116ada19fb.png)

**Comment by gideonthomas** [comment]
@sabrinang please provide your thoughts/concerns/suggestions on the mockup here - length, layout, etc.

One suggestion I have that I think we should discuss -- Mark's note is too long (and, in my opinion, delves too much into theme vs. what MozFest is about). I suggest moving this to either an About page or significantly tapering it down. It could also be a short pithy tweet length note from Mark that links to this longer text in the about page or a blog post or something.

**Comment by sabrinang** [comment]
Yes +1 I think Mark's note is text heavy on the full-width layout and since it is in blog form already on https://medium.com/mozilla-festival/mark-surman-on-mozfest-2019-4f3b932dd37a we can have short context for the link with a sentence or two and an image instead

**Comment by sabrinang** [comment]
Included shorter text option above feed on redpen: https://redpen.io/vuefbd37973f0c2a38
<img width="342" alt="image" src="https://user-images.githubusercontent.com/2492510/57737935-4ea7c080-7662-11e9-9231-8d7bc2fa2ef8.png">

**Comment by Pomax** [comment]
@sabrinang Is the over-banner-text fixed, or should that be CMS-controllable?

**Comment by gideonthomas** [comment]
@Pomax it should be CMS-editable if possible.

**Comment by Pomax** [comment]
It's possible, and has been implemented - how much of the main content that is in the comp would be CMS streamfield components? I recall talking about not trying to make the twitter stream a CMS component because it'd get too messy and take up too much time, any of the other content?

**Comment by gideonthomas** [comment]
- The banner content
- Banner button text
- Everything between the banner and the footer except the twitter feed

@sabrinang to confirm, everything between the banner and the footer was mocked up based on existing components?

**Comment by Pomax** [comment]
roger, in that case I think we can probably try to push this tomorrow and see how badly streamfield content doesn't quite cover it yet (or.. how brilliantly it already does! O_O)

It won't be "done", but it'll be at a stage where we can start refining while pages and content get built out.

**Comment by zee-moz** [comment]
@sabrinang when mark's note is shortened like this, does the full text live on medium, or elsewhere on the site? -- Oh wait, I see-- it's on medium, and appearing in the news feed below. Do we need it in both places?

**Comment by Pomax** [comment]
Implementation issue on the foundation side, for crosslinking: https://github.com/mozilla/foundation.mozilla.org/issues/3160

**Comment by Pomax** [comment]
For the footer, we're going with the mozfest specific signup, but no changes have been made wrt the social media buttons in the right column, so those will be pointing to the same things that foundation.moz does. If there are new links those should be pointing to instead, then as long as someone can put them in a comment, we can update the template to use those new links.

**Comment by Pomax** [comment]
What should the "watch now" button do, btw? Right now it's just a placeholder button but should this be a link to a page, or to a youtube video, or...?

**Comment by gideonthomas** [comment]
@zee-moz do you have links to the social accounts for MozFest? Twitter, instagram, etc.?

**Comment by zee-moz** [comment]
[Twitter](https://twitter.com/mozillafestival)

No Instagram, but there is a not very active hashtag (which sometimes randomly has Morrissey (aka Moz) in it)

**Comment by gideonthomas** [comment]
Thanks! @Pomax I think let's link out to twitter...instagram not sure if it makes sense here but we can leave it...and github, can probably be the same too.

**Comment by gideonthomas** [comment]
@sabrinang 	good to close this?
