### ISSUE TITLE
April Website Copy

### ISSUE THREAD

**Issue by zee-moz** [MozillaFoundation/mozfest-website-2019#11]
Copy drafted:
- [x] Dates, Tagline 
- [x] Short Blurb (25 words)
- [x] About MozFest & MozFest House (~87 words)
- [x] Note From Mark Surman (~263 words)
- [x] About the Festival Team  (~63 words)

[All copy is here. ](https://docs.google.com/document/d/1UWZuZGV5QFWhkWzMhhLo4uF-LbPKu-1MOJofjVxErVs/edit)

Reviews: 
- [ ] @Saallen 
- [x] @caltrider 
- [x] Mark approval on Note

cc @sabrinang

**Comment by gideonthomas** [comment]
@sabrinang check out the draft version of the mozfest page on wagtail. It should have content there. Sarah will make minor tweaks to the content. But, would you be able to give it a design uplift with the features it currently has?

@zee-moz to mention any feedback about this page as discussed in our call

**Comment by sabrinang** [comment]
Great thanks for putting content in, I updated the [draft](https://foundation.mozilla.org/cms/pages/335/view_draft/):
- moved colour banner up to top
- adjusted typography and spacing
- updated photo for mark's note
- edited image exposure for festival team photo
- sponsor section, I updated that link to mailto:sponsor@mozilla.org
- volunteer section I updated that link to https://wiki.mozilla.org/Mozfest/2019 (but it has no volunteer content)
- contact us via email link, updated to mailto:festival@mozilla.org
- simplified social icons (no square)

**Comment by gideonthomas** [comment]
Thanks @sabrinang looks great! @zee-moz what do you think?

**Comment by sabrinang** [comment]
@zee-moz @gideonthomas [Draft](https://foundation.mozilla.org/cms/pages/335/view_draft/) updated:
- image changed for mark's note and include photo of mark by his name
- updated order/spacing for festival team
- updated sponsorship email to jessew@mozillafoundation.org (since he is the contact on the sponsorship package)

**Comment by sabrinang** [comment]
live on https://foundation.mozilla.org/en/mozfest/
