### ISSUE TITLE
Mobile CTA Button Showing Incorrect Text

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-website-2019#12]
It appears that the call to action button at the bottom of the mobile version of Save the Date page says 'Take Action' can this be changed to 'Sign Up for Updates' or something similar? 

@zee-moz would you be able to recommend a line of text to put here?

Thanks!

![IMG_6FF679E45A73-1](https://user-images.githubusercontent.com/30226684/57069254-fbca2280-6ccb-11e9-838b-188aa192a5a3.jpeg)

**Comment by Pomax** [comment]
This is currently a hardcoded string I believe (looking at https://foundation.mozilla.org/cms/snippets/wagtailpages/signup/25/ it does not offer any way to change the button label) so this would be a change that would affect effect page with a signup CTA, not just this page.

@alanmoo it feels like a worthwhile effort to make that a controlled value in the signup with "Take action" as fallback?

**Comment by alanmoo** [comment]
Oh, I didn't see this until just now. @kristinashu mentioned it yesterday in Slack though, and I landed a fix as per her suggestion- the fixed button simply doesn't show up for newsletter signups (but the signup form is still available at the bottom of the page).
