### ISSUE TITLE
CfP- confirmation email copy request

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/mozfest-website-2019#14]
After people submit their MozFest session proposal via the website, we send them an automated confirmation email that contains:
** confirmation message that session was successfully submitted
** information they can jump back into the form and edit it afterwards.
** editing link to make changes 
** Travel Stipends - That if they need to request a stipend through a separate form on the website before July 1st. 
** Reminder that sessions will be curated until end of August and wranglers may email them for further information

Reference for 2018 email - https://github.com/mozilla/mozillafestival.org/issues/857

@KGorr  can you create the copy and @gideonthomas can trigger the automation of the email?

**Comment by KGorr** [comment]
Draft can be found here: https://docs.google.com/document/d/1chrNTWgciNHr1AFzV9szm6kFk-3-yiaEVD5u7IeoSOA/edit#heading=h.ela9ju93u8x1

**Comment by marcwalsh** [comment]
Thanks @KGorr - this has been added to the form.
