### ISSUE TITLE
Add 'Art and Culture' to Website

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/mozfest-website-2019#15]
Hi @gideonthomas and @zee-moz,

The content below is for the Art and Culture experience to appear on the website:

> From creative communities to web-native art and from online inspiration to digital design, the web fuels our creativity in a myriad of ways. But creativity also helps us fight for a healthy internet. 
> 
> In the Arts & Culture Experience we are championing creative practitioners, whose creativity shines critical light on contemporary innovation and lets us speculate about what may lie ahead.
> 
> We are celebrating important work being done by communities, galleries, libraries, archives and museums, who help to preserve arts and culture and make it accessible to all.
> Join us to build on the transformative potential of connected creativity to look ahead boldly and imagine exciting futures.
> 

Let's chat more at All Hands and see how this can appear on the website and how we can distinguish between experiences and spaces on the website.

Thanks!

**Comment by gideonthomas** [comment]
cc @sabrinang to make the UX call on how experiences show up on the website. We'll chat at All Hands/after to figure out what the difference between experiences and spaces are this year, and whether Queering and Neurodiversity are being messaged as spaces or experiences.

**Comment by gideonthomas** [comment]
Closing since we've moved it to the homepage.
