### ISSUE TITLE
About - June Version

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-website-2019#2]
### About
Ideas that needs discussion to clarify what we want and can achieve for June version.

**Content**
content from april version can live here in june? (when, where, mark's note, video etc.)

________________________________
### Draft Wireframe
Content for placement only.
<img width="300" src=https://user-images.githubusercontent.com/2492510/55363599-6f410000-5492-11e9-98d9-71985b32971b.png>

**Comment by gideonthomas** [comment]
@zee-moz what content do you want to feature on the homepage? Sabrina has mocked up an example above

Note that this is for June, not April.

**Comment by sabrinang** [comment]
Note: after our content chat today, we may go without an about page for June version
