### ISSUE TITLE
Participation Guidelines - June Version

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-website-2019#3]
### Community Participation Guidelines
Ideas that needs discussion to clarify what we want and can achieve for June version.

**Questions/Ideas**
does this include accessibility, inclusion/diversity, working open, raising issue blurbs, how to, pro tips or contact info from previous site and printed guide? or will that be on about page?

does this link to https://www.mozilla.org/en-US/about/governance/policies/participation/ or should this be something broader to have something on the foundation site?

where does this live? (festival site only or broader foundation site?)

previous page: https://mozillafestival.org/guidelines

**Comment by beccaklam** [comment]
@sabrinang I think we should base this page on last year's as a MVP and show it to stakeholders for feedback?

**Comment by gideonthomas** [comment]
adding to @beccaklam's suggestion, let's go with last year's solution and have it just be for MozFest for now, I think if we find it useful for a broader audience we can move it elsewhere later.

**Comment by sabrinang** [comment]
After today's content meeting, we confirmed that there will be a festival specific participation guidelines page.

Copy TBD on https://docs.google.com/document/d/12u63_FzPOEWvR1l_PLmT84Wj0nKpm3VgVuYofVo6m3E/edit#

**Comment by gideonthomas** [comment]
Done
