### ISSUE TITLE
Press/Media - June Version

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-website-2019#4]
### Press Media Kit
Ideas that needs discussion to clarify what we want and can achieve for June version.

**Questions/Ideas**
who is writing this content?
what do we want on this page?
where does this live? (this could be useful to have on the foundation's site about page too as a broader press kit)

previous page: https://mozillafestival.org/media

**Comment by gideonthomas** [comment]
@zee-moz do you know who's writing the content for this Press/Media page? If not, would you be able to find out from Sarah/Marc?
