### ISSUE TITLE
Team - June Version

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-website-2019#5]
### Team
Ideas that needs discussion to clarify what we want and can achieve for June version.

**Team**
include broader mozilla foundation context under team or about?

**Production & Wranglers**
how are we collecting bios?
how are we collecting photos?
how are we displaying people (mozilla pulse?)

**Volunteers**
include volunteer under team?
who is writing volunteer content? (do we still link to wiki?)
how do volunteers apply?

**Sponsors**
who is writing sponsor content?
how do sponsors apply?
do we display past year partners?

**Partners**
who is collecting these images and who are partners?
________________________________
### Draft Wireframe
Content for placement only.
<img width="300" src=https://user-images.githubusercontent.com/2492510/55364014-e4f99b80-5493-11e9-868f-86d0b8ccebd6.png>
<img width="300" src=https://user-images.githubusercontent.com/2492510/55363953-b4196680-5493-11e9-8bd7-bb519b636694.png>
<img width="300" src=https://user-images.githubusercontent.com/2492510/55363957-b4196680-5493-11e9-8832-caeebe520b4f.png>
<img width="300" src=https://user-images.githubusercontent.com/2492510/55363955-b4196680-5493-11e9-8119-0a2fdd3c0d2c.png>
<img width="300" src=https://user-images.githubusercontent.com/2492510/55363954-b4196680-5493-11e9-973c-9e68fef8674d.png>
<img width="300" src=https://user-images.githubusercontent.com/2492510/55363952-b380d000-5493-11e9-98ab-adcf6f0d843e.png>

**Comment by gideonthomas** [comment]
> include broader mozilla foundation context under team or about?

not sure I understand what you mean here

**Production & Wranglers**
Q. how are we collecting bios and photos?
A. Will check with Sarah/Marc

Q. how are we displaying people (mozilla pulse?)
A. Yeah I think that's easiest

**Volunteers**
Q. include volunteer under team?
Q. who is writing volunteer content? (do we still link to wiki?)
Q. how do volunteers apply?

A. @zee-moz what do you think?

**Sponsors**
Q. who is writing sponsor content?
Q. how do sponsors apply?
Q. do we display past year partners?

A. @zee-moz can you coordinate with Sarah and Juan about this?

**Partners**
Q. who is collecting these images and who are partners?
A. @zee-moz can you coordinate with Sarah/Marc to collect this, I believe they're communicating with partners.

**Comment by gideonthomas** [comment]
@sabrinang 	good to close?
