### ISSUE TITLE
Spaces - June Version

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-website-2019#6]
### Spaces
Ideas that needs discussion to clarify what we want and can achieve for June version.

**Questions/Ideas**
who will be writing space/experience description?
who will be writing space/experience narratives?
when will this be completed by?
who are the space wranglers?
who will be taking or collecting wrangler photos?
how will we be collecting bios? (mozilla pulse or other etc.)
________________________________
### Draft Wireframe
Content for placement only.

<img width="300" src=https://user-images.githubusercontent.com/2492510/55363472-00fc3d80-5492-11e9-8edb-bfed9727d496.png>

**Comment by sabrinang** [comment]
Copy from Zannah's June Content gdoc: https://docs.google.com/document/d/12u63_FzPOEWvR1l_PLmT84Wj0nKpm3VgVuYofVo6m3E/edit#

Updated redpen: https://redpen.io/wu787d46a2a87e6522
<img width="551" alt="image" src="https://user-images.githubusercontent.com/2492510/57735061-4480c480-7658-11e9-9928-4d6dba5d28a3.png">

- I placed space description context as intro paragraph and seen on all subpages
- I put Sessions and Theme on overview page
- each space is a subpage so users can grab URL to link directly and I thought it might get to long for a single page
- excluded "The 2019 Spaces are Web Literacy, Openness, Digital Inclusion, Decentralization, and Privacy & Security & Youth Zone." as it was getting to long for intro paragraph and since it is on subnav it might be repetitive
- also changed "explore the information on SPACES below.." to "above" since sub nav link to spaces are above

**Comment by gideonthomas** [comment]
@sabrinang good to close this?
