### ISSUE TITLE
Call for Proposals - June Version

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-website-2019#7]
### Call for Proposals
Ideas that needs discussion to clarify what we want and can achieve for June version.

**Questions/Ideas**
how are we accepting call for proposals?
where will the call for proposal form live? (external link to mozilla pulse or additional page)
who is writing call for proposal questions? (corresponding responses)
does comms cheat sheet link from the site or any other content?
when will content/decisions be completed by?
________________________________
### Draft Wireframe
Content for placement only.
![proposals](https://user-images.githubusercontent.com/2492510/55363022-a1e9f900-5490-11e9-8652-25ac6b339f96.png)

**Comment by sabrinang** [comment]
@gideonthomas mentioned we need a proposals page to display proposals and accepted proposals. Form will be on pulse (external link).

**Comment by beccaklam** [comment]
@gideonthomas Hey, Sabrina and I are a bit confused about where this will be hosted. Can you confirm if it will be on pulse or if we will host it on the MozFest website?

**Comment by gideonthomas** [comment]
Sorry, we can probably close this ticket. The CFP will be a google form so we just need to link to it on the website.

**Comment by sabrinang** [comment]
Form banner design issue filed here: https://github.com/MozillaFoundation/mozfest-design-2019/issues/19

@gideonthomas We shouldn't close yet we still need confirm answers to questions in this issue: who is writing form proposal questions and corresponding email responses and to track when it will be completed by. Also, who will be building the form on google forms?

**Comment by gideonthomas** [comment]
Ah gotcha, yeah so form proposal questions are here: https://docs.google.com/document/d/1H9Kxfkl1IHawSU70eBJWiVfhVPIhlf-zwE_axnCombA/edit and I will be building the google form.

**Comment by sabrinang** [comment]
Form banners updated in https://github.com/MozillaFoundation/mozfest-design-2019/issues/19#issuecomment-492862046

Let me know if that works with your cfp google form.

**Comment by gideonthomas** [comment]
Perfect, thanks @sabrinang, they look great! Assigning to myself to add to the form.
