### ISSUE TITLE
Speakers - August Version

### ISSUE THREAD

**Issue by sabrinang** [MozillaFoundation/mozfest-website-2019#9]
### Speakers
Ideas that needs discussion to clarify what we want and can achieve for August version.

**Questions/Ideas**
what info do we want to present? (talk name, time etc.)
how do we want to display speakers? (by people or by talk)
how do we want to display past speakers (by years) and what info do we want to include?
when will we get content by?
who is collecting bios and photos?
________________________________
### Draft Wireframe
Content for placement only.

<img width="300" src=https://user-images.githubusercontent.com/2492510/55365004-b41b6580-5497-11e9-9e4d-1636f63fabc1.png>

**Comment by sabrinang** [comment]
@KevZawacki if you have any content or thoughts to the questions/ideas above feel free to include them in this issue

**Comment by KevZawacki** [comment]
Thank you, @sabrinang 🙇  

If we're able to replicate exactly what the old MozFest site had, that would be great. If that's not possible, here are answers to your questions:

> what info do we want to present? (talk name, time etc.)

For 2019 speakers, let's do Name / Headshot / Twitter link / Talk or panel title / and Time

> how do we want to display speakers? (by people or by talk)

Let's do it by people. But, people on the same panel can be next to one another. 

> how do we want to display past speakers (by years) and what info do we want to include?

Yes, let's display them by year. And include Name / Headshot / Twitter link / and Talk or panel title

> when will we get content by?

I'll have a final line-up of 2019 speakers by July or early August

> who is collecting bios and photos?

I will! And will stash them in a Google Drive folder. Do you have the headshots of past speakers, from the old website? If not, I can re-collect those, too. 

Let me know how else I can help!

**Comment by gideonthomas** [comment]
Done: https://www.mozillafestival.org/speakers, and data entry for previous years will happen gradually.
